language: node_js
node_js:
  - '0.10'
before_script:
  - 'gem update --system'
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_success:
 - 'curl -l http://somewherebetween.us:8080/update_mobile_web.php'


